'use server';
/**
 * @fileOverview An AI assistant that analyzes mock sales and inventory data to generate natural language summaries or actionable insights.
 *
 * - aiDataInsightGenerator - A function that handles the generation of business insights.
 * - AIDataInsightGeneratorInput - The input type for the aiDataInsightGenerator function.
 * - AIDataInsightGeneratorOutput - The return type for the aiDataInsightGenerator function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AIDataInsightGeneratorInputSchema = z.object({
  totalSales: z.number().describe('The total sales figure for a period.'),
  totalOrders: z.number().describe('The total number of orders for a period.'),
  lowStockItems: z.array(
    z.object({
      productName: z.string().describe('The name of the product.'),
      stockQuantity: z.number().describe('The current stock quantity of the product.'),
    })
  ).describe('A list of products currently with low stock.'),
  topSellingProducts: z.array(
    z.object({
      productName: z.string().describe('The name of the top-selling product.'),
      totalRevenue: z.number().describe('The total revenue generated by this product.'),
    })
  ).describe('A list of top-selling products by revenue.'),
  monthlyRevenueTrends: z.array(
    z.object({
      month: z.string().describe('The month (e.g., "Jan", "Feb").'),
      revenue: z.number().describe('The total revenue for that month.'),
    })
  ).describe('Monthly revenue data to identify trends.'),
});

export type AIDataInsightGeneratorInput = z.infer<typeof AIDataInsightGeneratorInputSchema>;

const AIDataInsightGeneratorOutputSchema = z.object({
  insights: z.string().describe('A natural language summary and actionable insights.'),
});

export type AIDataInsightGeneratorOutput = z.infer<typeof AIDataInsightGeneratorOutputSchema>;

export async function aiDataInsightGenerator(input: AIDataInsightGeneratorInput): Promise<AIDataInsightGeneratorOutput> {
  return aiDataInsightGeneratorFlow(input);
}

const insightPrompt = ai.definePrompt({
  name: 'generateBusinessInsights',
  input: { schema: AIDataInsightGeneratorInputSchema },
  output: { schema: AIDataInsightGeneratorOutputSchema },
  prompt: `You are an AI business analyst for a grocery store. Your goal is to provide a concise and actionable summary of the store's performance based on the provided dashboard data. Highlight key trends, top performers, and critical concerns such as low stock.

**Current Dashboard Snapshot:**
- Total Sales: ${{{totalSales}}}
- Total Orders: {{{totalOrders}}}

**Low Stock Alerts:**
{{#if lowStockItems}}
{{#each lowStockItems}}
- {{productName}} ({{stockQuantity}} in stock)
{{/each}}
{{else}}
No immediate low stock concerns.
{{/if}}

**Top Selling Products (by Revenue):**
{{#if topSellingProducts}}
{{#each topSellingProducts}}
- {{productName}}: ${{{totalRevenue}}}
{{/each}}
{{else}}
No top selling product data available.
{{/if}}

**Monthly Revenue Trends:**
{{#if monthlyRevenueTrends}}
{{#each monthlyRevenueTrends}}
- {{month}}: ${{{revenue}}}
{{/each}}
{{else}}
No monthly revenue trend data available.
{{/if}}

Based on this data, provide a summary of the store's performance, identifying strengths, weaknesses, and actionable recommendations. Focus on clarity and conciseness, suitable for an administrator to quickly grasp the situation.
`,
});

const aiDataInsightGeneratorFlow = ai.defineFlow(
  {
    name: 'aiDataInsightGeneratorFlow',
    inputSchema: AIDataInsightGeneratorInputSchema,
    outputSchema: AIDataInsightGeneratorOutputSchema,
  },
  async (input) => {
    const { output } = await insightPrompt(input);
    return output!;
  }
);
